SKILL_VOCABULARY = {
    "Python": ["python", "py"],
    "Scikit-learn": ["sklearn", "scikit-learn"],
    "AWS": ["aws", "amazon web services"],
    "Java": ["java"],
    "JavaScript": ["javascript", "js"],
    "C++": ["c++", "cpp"],
    "C#": ["c#"],
    "SQL": ["sql"],
    "Git": ["git"],
    "Docker": ["docker"],
    "Kubernetes": ["kubernetes", "k8s"],
    "TensorFlow": ["tensorflow", "tf"],
    "PyTorch": ["pytorch", "torch"],
    "pandas": ["pandas"],
    "NumPy": ["numpy", "np"],
    "React": ["react"],
    "Node.js": ["node", "node.js"],
    "HTML": ["html"],
    "CSS": ["css"],
    "GitHub": ["github"],
    "JIRA": ["jira"],
    "Linux": ["linux"],
    "Windows": ["windows"],
    "macOS": ["macos", "macosx"],
    "Excel": ["excel"],
    "Tableau": ["tableau"],
    "Spark": ["spark"],
    "Hadoop": ["hadoop"],
    "Apache": ["apache"],
    "CI/CD": ["cicd", "ci/cd"],
    "Machine Learning": ["machine learning", "ml"],
    "Deep Learning": ["deep learning"],
    "Natural Language Processing": ["nlp"],
    "Azure": ["azure"],
    "GCP": ["gcp", "google cloud platform"],
    "Jenkins": ["jenkins"],
    "Kafka": ["kafka"],
    "Elasticsearch": ["elasticsearch"],
    "Celery": ["celery"],
    "Docker Compose": ["docker compose"],
    "GitLab": ["gitlab"],
}

SKILL_ALIASES = {
    "python": "Python",
    "py": "Python",
    "sklearn": "Scikit-learn",
    "scikit-learn": "Scikit-learn",
    "aws": "AWS",
    "amazon web services": "AWS",
    "java": "Java",
    "javascript": "JavaScript",
    "js": "JavaScript",
    "c++": "C++",
    "cpp": "C++",
    "c#": "C#",
    "sql": "SQL",
    "git": "Git",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "tensorflow": "TensorFlow",
    "tf": "TensorFlow",
    "pytorch": "PyTorch",
    "torch": "PyTorch",
    "pandas": "pandas",
    "numpy": "NumPy",
    "np": "NumPy",
    "react": "React",
    "node": "Node.js",
    "node.js": "Node.js",
    "html": "HTML",
    "css": "CSS",
    "github": "GitHub",
    "jira": "JIRA",
    "linux": "Linux",
    "windows": "Windows",
    "macos": "macOS",
    "macosx": "macOS",
    "excel": "Excel",
    "tableau": "Tableau",
    "spark": "Spark",
    "hadoop": "Hadoop",
    "apache": "Apache",
    "cicd": "CI/CD",
    "ci/cd": "CI/CD",
    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "deep learning": "Deep Learning",
    "nlp": "Natural Language Processing",
    "azure": "Azure",
    "gcp": "GCP",
    "google cloud platform": "GCP",
    "jenkins": "Jenkins",
    "kafka": "Kafka",
    "elasticsearch": "Elasticsearch",
    "celery": "Celery",
    "docker compose": "Docker Compose",
    "gitlab": "GitLab",
}

TEXT_CLEANING_OPTS = {
    "remove_urls": True,
    "remove_emails": True,
    "remove_phones": True,
    "normalize_whitespace": True,
    "lowercase": False,
}